# Generated by Django 4.2.1 on 2023-05-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_id_alter_orderitem_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='profit_rate',
        ),
    ]
