# Generated by Django 4.2.1 on 2023-05-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_options_remove_product_actual_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_rate',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
