# Generated by Django 4.2.1 on 2023-05-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='overall_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
