# Generated by Django 4.2.1 on 2023-05-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_overall_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=121231, max_length=6),
            preserve_default=False,
        ),
    ]
